const Images = {
  school1: require('../Images/school1.png'),
  park: require('../Images/park.png'),
  city: require('../Images/city.png'),
  desk: require('../Images/desk.png'),
  dad: require('../Images/dad.png'),
  mom: require('../Images/mom.png'),
  aunt: require('../Images/aunt.png'),
  uncle: require('../Images/uncle.png'),
  happy: require('../Images/happy.png'),
  sad: require('../Images/sad.png'),
  mad: require('../Images/mad.png'),
  idea: require('../Images/idea.png'),
  mark1: require('../Images/Mark0.jpg'),
  mark2: require('../Images/Mark1.jpg'),
  mark3: require('../Images/Mark2.jpg'),
  mark4: require('../Images/Mark3.jpg'),
  kate1: require('../Images/Kate0.jpg'),
  kate2: require('../Images/Kate1.jpg'),
  kate3: require('../Images/Kate2.jpg'),
  kate4: require('../Images/Kate3.jpg'),
  mary1: require('../Images/Mary0.jpg'),
  mary2: require('../Images/Mary1.jpg'),
  mary3: require('../Images/Mary2.jpg'),
  mary4: require('../Images/Mary3.jpg'),
  dante1: require('../Images/Dante0.jpg'),
  dante2: require('../Images/Dante1.jpg'),
  dante3: require('../Images/Dante2.jpg'),
  dante4: require('../Images/Dante3.jpg'),
}

export default Images;
